# Generated by Django 4.2.6 on 2024-06-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
