# Generated by Django 4.2.6 on 2024-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
