# Generated by Django 4.2.6 on 2024-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
