# Generated by Django 4.2.6 on 2024-06-22 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
