# Generated by Django 4.2.6 on 2024-06-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
